server:
  port: 11000
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
# 网络配置 路由转发
zuul:
  prefix: /springcloud
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      stripPrefix: false      # 不跳转前缀 就是转发带着/ad-sponsor/

